### PR TITLE
fix(build): @onu-ui path can not work normally

### PR DESCRIPTION
**Pull request by yzh990918**
After publish,the dist file directory doesn't has the `tsconfig.json`, We should use the relative path @zyyv .
image

### CODE REVIEW

**Comment by yzh990918** [comment]
After merge,try publish again.

**Comment by yzh990918** [comment]
Is there a better solution to this problem 😄 ? @zyyv

**Review by zyyv — APPROVED** [review]

**Comment by zyyv** [comment]
Try it.

**Comment by yzh990918** [comment]
> 
OK, try publish a new version.

**Pull request merged**
