### PR TITLE
chore: some details.

### PR DESCRIPTION
**Pull request by zhangmo8**

### CODE REVIEW

**Comment by zhangmo8** [comment]
Would I should run `pnpm sutb` before `pnpm dev`

**Comment by zhangmo8** [comment]
Chinese and English Contributing.md are out of sync.
I'm not sure which is right, or both.

**Comment by yzh990918** [comment]
> Would I should run `pnpm sutb` before `pnpm dev`

Just run `pnpm dev`.

**Comment by yzh990918** [comment]
> Chinese and English Contributing.md are out of sync. I'm not sure which is right, or both.

I'll take a look in the afternoon and change it .

**Comment by zhangmo8** [comment]
> > Would I should run `pnpm sutb` before `pnpm dev`
> 
> Just run `pnpm dev`.

When I first ran `pnpm dev` directly, I get the wrong `not found uno.css` in the `packages/components/index.ts`.

**Comment by zhangmo8** [comment]
I want to contact you via WeChat. If you would like

**Comment by yzh990918** [comment]
> I want to contact you via WeChat. If you would like

可以啊 直接加吧 16879082927

**Comment by yzh990918** [comment]
> 

Is it convenient to take a screenshot of the error?

**Review by yzh990918 — APPROVED** [review]

**Pull request merged**
