### PR TITLE
fix(card): update card unit test

### PR DESCRIPTION
**Pull request by yzh990918**

### CODE REVIEW

**Comment by yzh990918** [comment]
@zyyv Forgot to update the unit test for the card component 😃 .

**Comment by yzh990918** [comment]
> @zyyv The published CI failed, forgot to update the unit test for the card component 😃  .

**Review by zyyv — APPROVED** [review]

**Comment by zyyv** [comment]
Please use `squash` next time to keep commits clean. 😅

image

**Comment by yzh990918** [comment]
> > @zyyv The published CI failed, forgot to update the unit test for the card component 😃  .



> `squash` next time to keep commits

Sorry, it still need to republish the package. 1.0.9 failed to publish.

**Comment by yzh990918** [comment]
I am very sorry that the issue of package release has been repeated so many times, which has delayed you a lot of time 😭 @zyyv  .

**Pull request merged**
