### PR TITLE
fix: global import

### PR DESCRIPTION
**Pull request by priority3**
#72  fix register global components.

### CODE REVIEW

**Comment by priority3** [comment]
@chris-zhu should we change the `netlify.toml` to apply `docs/.vitepress/dist`, which confict with `netlify`


image

**Comment by yzh990918** [comment]
> #72 fix register global components.

Do you try to remove `OnuResolver` from `vite.config.ts` to test whether the global import works normally ?

**Comment by priority3** [comment]
> 

yeap，I delete `onu-ui`  under `play/src/modules` and add `onu` in `main.ts`

**Comment by priority3** [comment]
> > #72 fix register global components.
> 
> Do you try to remove `OnuResolver` from `vite.config.ts` to test whether the global import works normally ?

yeap , I delete `onu-ui` file under the `play/src/modules` , remove `OnuResolver` from `vite.config.ts` and import `onu` in `main.ts`, 
```js
import 'onu' from 'onu-ui'
app.use(onu)
```
it's work well by the test

**Comment by yzh990918** [comment]
> 

Nice fixed @chris-zhu .

**Comment by zyyv** [comment]
Ok, I'll take a look later, I think I can optimize the `resolver`.

**Comment by zyyv** [comment]
> @chris-zhu should we change the `netlify.toml` to apply `docs/.vitepress/dist`, which confict with `netlify`

Updated on #87

**Comment by priority3** [comment]
> > @chris-zhu should we change the `netlify.toml` to apply `docs/.vitepress/dist`, which confict with `netlify`
> 
> Updated on #87

great, I will update it later if that pr had merged,

**Comment by priority3** [comment]
> > > @chris-zhu should we change the `netlify.toml` to apply `docs/.vitepress/dist`, which confict with `netlify`
> > 
> > 
> > Updated on #87
> 
> great, I will update it later if that pr had merged,

done

**Comment by yzh990918** [comment]
How's the subsequent refactoring going 😄 . @zyyv

**Comment by priority3** [comment]
> resolver

or say, is any proposal for `reslover`, I wanna do this 😂

**Comment by yzh990918** [comment]
> > resolver
> 
> or say, is any proposal for `reslover`, I wanna do this 😂

https://github.com/onu-ui/onu-ui/issues/72. Here are some temporary todos that you can refer to.

**Comment by zyyv** [comment]
I updated it in the latest code, but it's still a little weird. Do you think this will be a problem?
https://github.com/onu-ui/onu-ui/blob/75c002a45b9df86ab7f069a258985b2a6b2f724b/packages/onu-ui/src/resolver.ts#L6-L9
https://github.com/onu-ui/onu-ui/blob/75c002a45b9df86ab7f069a258985b2a6b2f724b/packages/onu-ui/package.json#L27-L31

**Comment by yzh990918** [comment]
> I updated it in the latest code, but it's still a little weird. Do you think this will be a problem?
> 
> https://github.com/onu-ui/onu-ui/blob/75c002a45b9df86ab7f069a258985b2a6b2f724b/packages/onu-ui/src/resolver.ts#L6-L9
> 
> 
> https://github.com/onu-ui/onu-ui/blob/75c002a45b9df86ab7f069a258985b2a6b2f724b/packages/onu-ui/package.json#L27-L31

All components are already exported in the entry, so adding `/components` path may not be necessary. `OnuResolver`is woking propely. You can try restore it.

**Comment by yzh990918** [comment]
> I updated it in the latest code, but it's still a little weird. Do you think this will be a problem?
> 
> https://github.com/onu-ui/onu-ui/blob/75c002a45b9df86ab7f069a258985b2a6b2f724b/packages/onu-ui/src/resolver.ts#L6-L9
> 
> 
> https://github.com/onu-ui/onu-ui/blob/75c002a45b9df86ab7f069a258985b2a6b2f724b/packages/onu-ui/package.json#L27-L31

After restore it. It works fine.

image

**Comment by yzh990918** [comment]
fixed #95

**Comment by zyyv** [comment]
Thank you for the discovery, please forgive me for closing it soon. @priority3

**Pull request closed without merging**
