### PR TITLE
feat(component): add message

### LINKED ISSUE #43: New componet: Message

### PR DESCRIPTION
**Pull request by priority3**
close #43 
finished basic func of message component,a few test,and message component docs,I will maintain it . @chris-zhu

### CODE REVIEW

**Comment by yzh990918** [comment]
@priority3 I prefer to set a basic icon when a message type is given, and then set a custom icon to overrite, and then the close icon style can be centered with the content, of course, it's just my personal suggestion 🤣.

**Comment by priority3** [comment]
> suggestion

Thanks for your suggestion,I will add default icon with every theme,privide the `icon` to overrite,and it's a good idea that the close icon style  is centered with the content，I will improve it later😜

**Comment by priority3** [comment]
> @priority3 I prefer to set a basic icon when a message type is given, and then set a custom icon to overrite, and then the close icon style can be centered with the content, of course, it's just my personal suggestion 🤣.

Thanks for your suggestion,I will add default icon with every theme,privide the icon to overrite,and it's a good idea that the close icon style is centered with the content，I will improve it later😜

**Comment by priority3** [comment]
I finished the default icon and closeable style, and fixed docs and playground @yzh990918  @chris-zhu 🤒

**Pull request merged**
