### PR TITLE
docs(pref): add component documentation specifications and  beautify component documentation.

### PR DESCRIPTION
**Pull request by yzh990918**
preview: https://onu-2h0cf70zw-251205668.vercel.app/components/button.html

### CODE REVIEW

**Comment by zyyv** [comment]
Why the button blured have a border?
image
Button code has not changed, this change is mainly for the document, may need to check button style

**Comment by priority3** [comment]
image

This introduces a css , which conflicts with the style of `o-button-base` , I can fix it by overwrite css style in docs , it seems to have this problem in previous versions of docs, but I don't know where is it come from?

**Comment by yzh990918** [comment]
> image
> 
> This introduces a css , which conflicts with the style of `o-button-base` , I can fix it by overwrite css style in docs , it seems to have this problem in previous versions of docs, but I don't know where is it come from?

might be the vitepress default style caught it

**Comment by yzh990918** [comment]
> Why the button blured have a border? image Button code has not changed, this change is mainly for the document, may need to check button style

fixed by change !outline-none to !focus:outline-none, https://stackoverflow.com/questions/69981112/focusoutline-none-not-working-tailwind-css-with-laravel 
preview: https://onu-9c4l9h8bm-251205668.vercel.app/

**Review by zyyv — APPROVED** [review]

**Pull request merged**
